In [1]:
import pandas as pd
import numpy as np

import nltk

In [3]:
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')
tokenizer.tokenize('Eighty-seven miles played to go, yet. 78mmb, zk19900,,,...... Onward!')

['Eighty',
 'seven',
 'miles',
 'played',
 'to',
 'go',
 'yet',
 '78mmb',
 'zk19900',
 'Onward']

In [15]:
#nltk.download()

In [16]:
#nltk.download('punkt')

In [4]:
data = 'I am not doing . '
data.strip()

'I am not doing .'

In [7]:
text = "In Brazil they drive on the right-hand side of the road. Brazil has a large coastline on the eastern side of South America"

import nltk.corpus
from nltk.tokenize import word_tokenize

token = word_tokenize(text.lower()); token

['in',
 'brazil',
 'they',
 'drive',
 'on',
 'the',
 'right-hand',
 'side',
 'of',
 'the',
 'road',
 '.',
 'brazil',
 'has',
 'a',
 'large',
 'coastline',
 'on',
 'the',
 'eastern',
 'side',
 'of',
 'south',
 'america']

In [6]:
from nltk.probability import FreqDist

fdist = FreqDist(token); fdist 

FreqDist({'the': 3, 'brazil': 2, 'on': 2, 'side': 2, 'of': 2, 'in': 1, 'they': 1, 'drive': 1, 'right-hand': 1, 'road': 1, ...})

In [20]:
fdist.most_common(10)

[('the', 3),
 ('brazil', 2),
 ('on', 2),
 ('side', 2),
 ('of', 2),
 ('in', 1),
 ('they', 1),
 ('drive', 1),
 ('right-hand', 1),
 ('road', 1)]

Stemming - converting tokens to it's base form. more cruder way of removing suffix. Doesn't take linguistic approach so the base form might not have the meaning. It's generally fast as it doesn't have to look up ine the stored data dictonary.

Lemmatization - Understands the context and convert Tokens to it's meaningful base form that has dictionary meaning. Might take time with a huge data.





In [21]:
from nltk.stem import PorterStemmer

stem = [PorterStemmer().stem(i) for i in token]; stem[:10]

['in',
 'brazil',
 'they',
 'drive',
 'on',
 'the',
 'right-hand',
 'side',
 'of',
 'the']

In [22]:
from nltk.stem import WordNetLemmatizer

#nltk.download('wordnet')
lemma = [WordNetLemmatizer().lemmatize(i) for i in token]; lemma

['in',
 'brazil',
 'they',
 'drive',
 'on',
 'the',
 'right-hand',
 'side',
 'of',
 'the',
 'road',
 '.',
 'brazil',
 'ha',
 'a',
 'large',
 'coastline',
 'on',
 'the',
 'eastern',
 'side',
 'of',
 'south',
 'america']

In [23]:
from nltk.corpus import stopwords
a = set(stopwords.words('english'))

nltk.download('stopwords')

[i for i in token if i not in a]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\p192\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['brazil',
 'drive',
 'right-hand',
 'side',
 'road',
 '.',
 'brazil',
 'large',
 'coastline',
 'eastern',
 'side',
 'south',
 'america']

In [24]:
### pos-tag

nltk.pos_tag(token)

[('in', 'IN'),
 ('brazil', 'NN'),
 ('they', 'PRP'),
 ('drive', 'VBP'),
 ('on', 'IN'),
 ('the', 'DT'),
 ('right-hand', 'JJ'),
 ('side', 'NN'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('road', 'NN'),
 ('.', '.'),
 ('brazil', 'NN'),
 ('has', 'VBZ'),
 ('a', 'DT'),
 ('large', 'JJ'),
 ('coastline', 'NN'),
 ('on', 'IN'),
 ('the', 'DT'),
 ('eastern', 'JJ'),
 ('side', 'NN'),
 ('of', 'IN'),
 ('south', 'NN'),
 ('america', 'NN')]

In [25]:
# Named Entity Recognization (NER) - Detecting named entities such as place name, person name, location etc.

from nltk import ne_chunk

x = nltk.pos_tag(token)
x
#ne_chunk(nltk.pos_tag(x))

[('in', 'IN'),
 ('brazil', 'NN'),
 ('they', 'PRP'),
 ('drive', 'VBP'),
 ('on', 'IN'),
 ('the', 'DT'),
 ('right-hand', 'JJ'),
 ('side', 'NN'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('road', 'NN'),
 ('.', '.'),
 ('brazil', 'NN'),
 ('has', 'VBZ'),
 ('a', 'DT'),
 ('large', 'JJ'),
 ('coastline', 'NN'),
 ('on', 'IN'),
 ('the', 'DT'),
 ('eastern', 'JJ'),
 ('side', 'NN'),
 ('of', 'IN'),
 ('south', 'NN'),
 ('america', 'NN')]

In [26]:
### Lexion based Analysis - no labelled data but sets of words/phrases or heuristics or predefined rules. It's based on set of lexical and syntactic features of the text where set of positive and negative words define the target.

In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/amazon.csv')
df

reviewText  Positive
0      This is a one of the best apps acording to a b...         1
1      This is a pretty good version of the game for ...         1
2      this is a really cool game. there are a bunch ...         1
3      This is a silly game and can be frustrating, b...         1
4      This is a terrific game on any pad. Hrs of fun...         1
...                                                  ...       ...
19995  this app is fricken stupid.it froze on the kin...         0
19996  Please add me!!!!! I need neighbors! Ginger101...         1
19997  love it!  this game. is awesome. wish it had m...         1
19998  I love love love this app on my side of fashio...         1
19999  This game is a rip off. Here is a list of thin...         0

[20000 rows x 2 columns]

In [28]:
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')


#df['reviewText'] = df['reviewText'].apply(lambda x: word_tokenize(x.lower()))
df['reviewText'] = df['reviewText'].apply(lambda x: tokenizer.tokenize(x.lower()))
df['reviewText'] = df['reviewText'].apply(lambda x: [i for i in x if i not in stopwords.words('english')])
df['reviewText'] = df['reviewText'].apply(lambda x: [WordNetLemmatizer().lemmatize(i) for i in x])
#df['reviewText'] = df['reviewText'].apply(lambda x: tokenizer.tokenize(x))
df['reviewText']

0        [one, best, apps, acording, bunch, people, agr...
1        [pretty, good, version, game, free, lot, diffe...
2        [really, cool, game, bunch, level, find, golde...
3        [silly, game, frustrating, lot, fun, definitel...
4        [terrific, game, pad, hr, fun, grandkids, love...
                               ...                        
19995    [app, fricken, stupid, froze, kindle, wont, al...
19996    [please, add, need, neighbor, ginger1016, than...
19997    [love, game, awesome, wish, free, stuff, house...
19998    [love, love, love, app, side, fashion, story, ...
19999    [game, rip, list, thing, make, better, bull, f...
Name: reviewText, Length: 20000, dtype: object

In [29]:
df['reviewText_2'] = df['reviewText'].apply(lambda x: ' '.join(x)); df['reviewText_2']

0        one best apps acording bunch people agree bomb...
1        pretty good version game free lot different le...
2        really cool game bunch level find golden egg s...
3        silly game frustrating lot fun definitely reco...
4        terrific game pad hr fun grandkids love great ...
                               ...                        
19995    app fricken stupid froze kindle wont allow pla...
19996    please add need neighbor ginger1016 thanks bun...
19997    love game awesome wish free stuff house cost m...
19998    love love love app side fashion story fight wo...
19999    game rip list thing make better bull first nee...
Name: reviewText_2, Length: 20000, dtype: object

In [30]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [31]:
# Initialize Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

def analyser(text):
    scores = analyzer.polarity_scores(text)
    sentiment = 1 if scores['pos'] > 0 else 0
    return sentiment

# Apply this to out dataframe

df['scores'] = df['reviewText_2'].apply(analyser); df

reviewText  Positive  \
0      [one, best, apps, acording, bunch, people, agr...         1   
1      [pretty, good, version, game, free, lot, diffe...         1   
2      [really, cool, game, bunch, level, find, golde...         1   
3      [silly, game, frustrating, lot, fun, definitel...         1   
4      [terrific, game, pad, hr, fun, grandkids, love...         1   
...                                                  ...       ...   
19995  [app, fricken, stupid, froze, kindle, wont, al...         0   
19996  [please, add, need, neighbor, ginger1016, than...         1   
19997  [love, game, awesome, wish, free, stuff, house...         1   
19998  [love, love, love, app, side, fashion, story, ...         1   
19999  [game, rip, list, thing, make, better, bull, f...         0   

                                            reviewText_2  scores  
0      one best apps acording bunch people agree bomb...       1  
1      pretty good version game free lot different le...       1  
2      really cool game bunch level find golden egg s...       1  
3      silly game frustrating lot fun definitely reco...       1  
4      terrific game pad hr fun grandkids love great ...       1  
...                                                  ...     ...  
19995  app fricken stupid froze kindle wont allow pla...       0  
19996  please add need neighbor ginger1016 thanks bun...       1  
19997  love game awesome wish free stuff house cost m...       1  
19998  love love love app side fashion story fight wo...       1  
19999  game rip list thing make better bull first nee...       1  

[20000 rows x 4 columns]

In [32]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(df['Positive'], df['scores']))

from sklearn.metrics import classification_report
print(classification_report(df['Positive'], df['scores']))

[[ 1063  3704]
 [  536 14697]]
              precision    recall  f1-score   support

           0       0.66      0.22      0.33      4767
           1       0.80      0.96      0.87     15233

    accuracy                           0.79     20000
   macro avg       0.73      0.59      0.60     20000
weighted avg       0.77      0.79      0.75     20000



### ML- Based


In [34]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split 

In [35]:
countvect = CountVectorizer()                               #countvectorizer model object
countvect_2 = countvect.fit_transform(df['reviewText_2'])   #create sparse matrix of documents and vector counts

In [37]:
features = countvect.get_feature_names_out() #features

df_sparse = pd.DataFrame(countvect_2.todense(), columns = features)

feature_counts = np.sum(df_sparse.values, axis = 0)

feature_counts_df = pd.DataFrame(dict(features = features, counts = feature_counts))
feature_counts_df.sort_values(by = 'counts', ascending=False, inplace = True); feature_counts_df.head()

features  counts
1187      app   10879
6415     game    6899
9070     love    4302
6813    great    4092
8850     like    4042

### Naive - Bayes Modeling

In [304]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB


In [305]:
X_train, X_test, y_train, y_test = train_test_split(countvect_2.todense(), df['Positive'], test_size=0.2, random_state=1)
nb_clf = GaussianNB().fit(X_train, y_train)
y_pred = nb_clf.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

0.5325
[[ 711  236]
 [1634 1419]]
              precision    recall  f1-score   support

           0       0.30      0.75      0.43       947
           1       0.86      0.46      0.60      3053

    accuracy                           0.53      4000
   macro avg       0.58      0.61      0.52      4000
weighted avg       0.73      0.53      0.56      4000



In [306]:
#### Not good let's tune it

In [307]:
import string
import regex as re
# Removing twitter handles, punctuation, extra spaces, numbers and special characters
def remove_noise(text):
# #      text = re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+#]|[!*\(\),]|'\
# #                        '(?:%[0-9a-fA-F][0-9a-fA-F]))+','', text)
# #     text = ''.join([char if char not in string.punctuation else ' ' for char in text])
#      text = re.sub(' +', ' ', text)
#      text = re.sub('[0–9]+', '', text)
#      text = re.sub('[^A-Za-z0–9_. ]+','',text) 

    text = re.sub(r"[^A-Za-z0-9\-]", " ", text)
    return text

In [308]:
countvect_tuned = CountVectorizer(stop_words='english', min_df=0.2, max_df=0.5, ngram_range=(1, 3)) 

#min_df - ignores tokens which are present in less than 20% documents.
#max_df - ignores tokens which are present in more than 50% of the document.
#max_features - limiting vocabulary size to 50. Selectly mots common 50 tokens.
#binary - if set to False, then counts aren't taken only 1 and 0 are imputed.
#processor = noise removal function etc.

countvect_tuned_vector = countvect_tuned.fit_transform(df['reviewText_2'])

In [309]:
features = countvect_tuned.get_feature_names() #features

df_sparse = pd.DataFrame(countvect_tuned_vector.todense(), columns = features)

feature_counts = np.sum(df_sparse.values, axis = 0)
feature_counts_df = pd.DataFrame(dict(features = features, counts = feature_counts))
feature_counts_df.sort_values(by = 'counts', ascending=False, inplace = True); feature_counts_df.head()

features  counts
20       app   10879
91      game    6899
138     love    4302
101    great    4092
128     like    4042

In [310]:
df_sparse.shape

(20000, 254)

In [311]:
X_train, X_test, y_train, y_test = train_test_split(countvect_tuned_vector.todense(), df['Positive'], test_size=0.2, random_state=1)
nb_clf = GaussianNB().fit(X_train, y_train)
y_pred = nb_clf.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('Train accuracy: {}'.format(accuracy_score(y_train, nb_clf.predict(X_train))))
print('Test accuracy: {}'.format(accuracy_score(y_test, y_pred)))
 
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Train accuracy: 0.7453125
Test accuracy: 0.74075
[[ 820  127]
 [ 910 2143]]
              precision    recall  f1-score   support

           0       0.47      0.87      0.61       947
           1       0.94      0.70      0.81      3053

    accuracy                           0.74      4000
   macro avg       0.71      0.78      0.71      4000
weighted avg       0.83      0.74      0.76      4000



### Tf-IDF

In [312]:
from sklearn.feature_extraction.text import TfidfVectorizer   
idf_vect = TfidfVectorizer()                               #countvectorizer model object
idf_vect_2 = idf_vect.fit_transform(df['reviewText_2']) 

In [313]:
features = idf_vect.get_feature_names() #features

df_sparse = pd.DataFrame(idf_vect_2.todense(), columns = features)

feature_counts = np.sum(df_sparse.values, axis = 0)

feature_counts_df = pd.DataFrame(dict(features = features, counts = feature_counts))
feature_counts_df.sort_values(by = 'counts', ascending=False, inplace = True); feature_counts_df.head()

features      counts
1187      app  891.530160
6415     game  760.771047
9070     love  546.923368
6813    great  507.314671
8850     like  486.569063

In [314]:
X_train, X_test, y_train, y_test = train_test_split(idf_vect_2.todense(), df['Positive'], test_size=0.2, random_state=1)
nb_clf = GaussianNB().fit(X_train, y_train)
y_pred = nb_clf.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('Train accuracy: {}'.format(accuracy_score(y_train, nb_clf.predict(X_train))))
print('Test accuracy: {}'.format(accuracy_score(y_test, y_pred)))
 
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Train accuracy: 0.7114375
Test accuracy: 0.53125
[[ 702  245]
 [1630 1423]]
              precision    recall  f1-score   support

           0       0.30      0.74      0.43       947
           1       0.85      0.47      0.60      3053

    accuracy                           0.53      4000
   macro avg       0.58      0.60      0.52      4000
weighted avg       0.72      0.53      0.56      4000



### Tuned - IDF

In [315]:
from sklearn.feature_extraction.text import TfidfVectorizer   
idf_vect = TfidfVectorizer(stop_words='english', min_df=0.01, max_df=.7, ngram_range=(1, 3))                            



idf_vect_2 = idf_vect.fit_transform(df['reviewText_2']) 

In [316]:
X_train, X_test, y_train, y_test = train_test_split(idf_vect_2.todense(), df['Positive'], test_size=0.2, random_state=1)
nb_clf = GaussianNB().fit(X_train, y_train)
y_pred = nb_clf.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('Train accuracy: {}'.format(accuracy_score(y_train, nb_clf.predict(X_train))))
print('Test accuracy: {}'.format(accuracy_score(y_test, y_pred)))
 
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Train accuracy: 0.7678125
Test accuracy: 0.764
[[ 813  134]
 [ 810 2243]]
              precision    recall  f1-score   support

           0       0.50      0.86      0.63       947
           1       0.94      0.73      0.83      3053

    accuracy                           0.76      4000
   macro avg       0.72      0.80      0.73      4000
weighted avg       0.84      0.76      0.78      4000

